Use pinned hashes for magic-folder.
gridsync/gridsync pull request #355
Opened 2021-06-18 18:59 UTC by tomprince

2021-07-16 08:00 UTC, tomprince commented
I don't *think* the remaining failures are related to my changes.

2021-07-20 18:05 UTC, crwood requested changes
Thanks for this. The Windows failures are due to the broken `magic-folder leave` functionality (which, I can see, you are already aware of) but the macOS failure seems to be new. Please see my comment for a suggested fix.

2021-07-20 18:05 UTC, crwood commented on Makefile
> +	python $(SCRIPTS)/reproducible-pip.py install --require-hashes -r requirements/base.txt && \
Ironically, this line is _breaking_ reproducibility on macOS (as per [this test run](https://github.com/gridsync/gridsync/pull/355/checks?check_run_id=3116409975)), due, apparently, to the pyrsistent 0.16.1 wheel not building in a deterministic fashion... Can you try pip installing the requirements with `CFLAGS=-g0` and see if doing so will result in a pass? (I had to do this previously in order to build reproducible tahoe binaries; see, e.g., the `frozen-tahoe` make target in the same Makefile).

2021-07-21 03:40 UTC, crwood approved these changes
Passing now with `CFLAGS=-g0` -- thanks a bunch!

2021-07-21 03:40 UTC, merged